version: "3"

services:
  webservices:
    userns_mode: keep-id
    image: mcr.microsoft.com/devcontainers/java:1-17-bullseye
    command: sleep infinity
    volumes:
      - "./:/home/vscode/workspace/:z"
      - ".vscode-server/:/home/vscode/.vscode-server/:z"

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
